version: 2

models:
  - name: dim_products
    description: "Product dimension table containing information on each unique product in the catalog."
    columns:
      - name: product_key
        description: "Primary surrogate key for each product."
        tests:
          - unique
          - not_null
      - name: product_id
        description: "ASIN or unique product identifier from the source data."
        tests:
          - not_null
      - name: category_sales_rank
        description: "Sales rank within the primary category."
      - name: primary_category
        description: "Primary category to which the product belongs."
      - name: product_name
        description: "Product name or title."
      - name: product_description
        description: "Detailed description of the product."
      - name: list_price
        description: "List price of the product."
      - name: brand_name
        description: "Brand or manufacturer of the product."

  - name: dim_date
    description: "Date dimension table used for organizing time-based data, with detailed date attributes."
    columns:
      - name: date_key
        description: "Primary surrogate key for each date in YYYYMMDD format."
        tests:
          - unique
          - not_null
      - name: date
        description: "Actual date."
        tests:
          - not_null
      - name: year
        description: "Year part of the date."
        tests:
          - not_null
      - name: month
        description: "Month part of the date."
        tests:
          - not_null
      - name: day
        description: "Day part of the date."
        tests:
          - not_null
      - name: day_of_week
        description: "Day of the week (1=Sunday, 7=Saturday)."
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7]
